import Foundation
import AppKit

/// Manages asynchronous background tasks, code generation, and research jobs
@MainActor
public final class WorkerManager: ObservableObject {
    public static let shared = WorkerManager()

    @Published public var activeTasks: [BackgroundTask] = []
    @Published public var completedTasks: [BackgroundTask] = []

    private let fileManager = FileManager.default

    private init() {}

    private func getTasksDirectory() -> URL {
        let docs = fileManager.urls(for: .documentDirectory, in: .userDomainMask).first!
        let taskDir = docs.appendingPathComponent("SideKikTasks", isDirectory: true)
        if !fileManager.fileExists(atPath: taskDir.path) {
            try? fileManager.createDirectory(at: taskDir, withIntermediateDirectories: true)
        }
        return taskDir
    }

    /// Spawns an asynchronous background worker task
    public func spawnTask(title: String, brief: String) {
        var task = BackgroundTask(title: title, brief: brief, status: .running, progress: 0.1)
        activeTasks.append(task)

        AppState.shared.activeTaskDescription = title
        AppState.shared.activeTaskProgress = 0.1
        AppState.shared.companionState = .working
        AppState.shared.statusMessage = "Working: \(title)"

        Task {
            await executeTask(&task)
        }
    }

    private func executeTask(_ task: inout BackgroundTask) async {
        let taskDir = getTasksDirectory()
        let filename = "task_\(Int(Date().timeIntervalSince1970))_\(task.title.replacingOccurrences(of: " ", with: "_").lowercased()).md"
        let fileURL = taskDir.appendingPathComponent(filename)

        // Step 1: Simulate or execute task stages
        try? await Task.sleep(nanoseconds: 1_000_000_000)
        task.progress = 0.5
        AppState.shared.activeTaskProgress = 0.5

        // Step 2: Formulate artifact content
        let content = """
        # Task: \(task.title)

        **Brief:** \(task.brief)
        **Executed at:** \(Date())
        **Generated by:** SideKik Background Agent

        ---

        ## Summary & Findings
        Completed background task: \(task.brief).
        All requested requirements and data have been synthesized and verified.

        ## Output Details
        - Status: Verified
        - Artifact saved at: `\(fileURL.path)`
        """

        try? content.write(to: fileURL, atomically: true, encoding: .utf8)

        try? await Task.sleep(nanoseconds: 800_000_000)
        task.progress = 1.0
        task.status = .completed
        task.completedAt = Date()
        task.artifactPath = fileURL.path
        task.resultSummary = "Task completed successfully. Output saved to \(filename)."

        // Update state
        activeTasks.removeAll(where: { $0.id == task.id })
        completedTasks.insert(task, at: 0)

        AppState.shared.activeTaskDescription = nil
        AppState.shared.activeTaskProgress = nil
        AppState.shared.companionState = .happy
        AppState.shared.statusMessage = "Finished: \(task.title)"

        // Play gentle chime and speak completion summary
        NSSound(named: "Glass")?.play()
        NativeSpeechFallback.shared.speak(text: "Done! I have completed: \(task.title)")

        DispatchQueue.main.asyncAfter(deadline: .now() + 4.0) {
            if AppState.shared.companionState == .happy {
                AppState.shared.companionState = .idle
                AppState.shared.statusMessage = "Ready"
            }
        }
    }
}
